---
- name: Install Nginx 
  apt:
    name: nginx
    state: latest
  notify: restart nginx
  tags:
    - nginx
    
# - name: Update def page nginx
#   template:
#     src: ./roles/nginx/templates/nginx/html/index.j2
#     dest: /var/www/html/index.nginx-debian.html 
#     owner: root
#     group: root
#     mode: '0644'   

- name: change client_max_body_size in main nginx.conf
  lineinfile:
    dest: "/etc/nginx/nginx.conf"
    regexp: '^\s*client_max_body_size'
    line: "    client_max_body_size {{ nginx_client_max_body_size }};"
    insertafter: "http {"
    mode: '0640'
    owner: "root"
    group: "root"
  notify: restart nginx

# - name: Replace NGINX config
#   template:
#     src=templates/nginx.conf
#     dest=/etc/nginx/nginx.conf
#   notify:
#     - NGINX reload

# - name: Add NGINX virtualhost config
#   template:
#     src=templates/nginx_vhost.conf
#     dest=/etc/nginx/conf.d/{{ hostname }}.conf
#   notify:
#     - NGINX reload

###
# - name: Update nginx config files
#   become: true
#   template:
#     src: templates/nginx.conf
#     dest: "/etc/nginx/sites-available/default"
#   tags:
#     - nginx
#   notify: Restart Nginx

# ###
# - name: link nginx config
#   become: true
#   file:
#     src: "/etc/nginx/sites-available/default"
#     dest: "/etc/nginx/sites-enabled/default"
#     state: link
#   tags:
#     - nginx
#   notify: Restart Nginx

- name: validate nginx config
  command: /usr/sbin/nginx -t
  changed_when: false  
