---
- name: Install apt packages
  apt:
    cache_valid_time: 3600
    update_cache: yes
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - mc
    - git
    - tree
    - curl
    - htop
    - make
    - apt-transport-https
    - ca-certificates
   
