---
- name: Install apt packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - "git"
    - "copyq"
    - "gnome-tweaks"

- name: Install Snap packages with --classic flag
  snap:
    classic: yes
    name:
      - postman
      - code
      - firefox
      - spotify
      - docker

- name: Install Snap packages with --channel flag
  snap:
    name: "{{ item.name }}"
    channel: "{{ item.channel }}"
    classic: yes
  loop:
    - { name: 'dotnet-sdk', channel: '5.0/stable'}
    - { name: 'node', channel: '12/stable'}
