---
## sudo apt-get update 
# - name: Update apt packages
#   apt:
#     update_cache: yes
#     cache_valid_time: 3600 

- name: Install packages MC only when the apt process is not locked
  apt:
    update_cache: yes
    name: mc
    state: present
  register: apt_action
  retries: 40
  delay: 10
  until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)

- name: Install utils
  apt:
    update_cache: yes
    pkg:
    - git
    - apt-transport-https
    - ca-certificates
    - curl
    - zip
    - tree
    - make
    - htop
    - iotop       
    autoremove: yes
