---
- name: "APT - Add Docker GPG key"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Install libcurl4 package
  become: yes
  become_user: root
  apt:
    name: libcurl4
    state: present
    update_cache: yes

- name: "APT - Add Docker repository"
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
    state: present
    filename: docker

- name: Install utility packages common to all hosts
  apt:
    update_cache: yes
    name:
      - aptitude
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
    autoclean: yes    

- name: "APT - install 'docker-ce'"
  apt:
    name: "docker-ce"
    update_cache: yes