---
- name: add key
  command: apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

- name: add deb repo
  command: touch /etc/apt/sources.list.d/docker.list

- name: add deb repo
  lineinfile: 
    dest: "/etc/apt/sources.list.d/docker.list" 
    line: "{{ item }}"
  with_items:
    - "deb https://apt.dockerproject.org/repo ubuntu-xenial main"

- name: install docker
  apt: 
    name: docker-engine
    update_cache: yes
    state: present