---
- name: Check current docker-compose version {{ ansible_distribution_version }}
  command: docker-compose --version
  register: docker_compose_current_version
  changed_when: false
  failed_when: false

- name: Delete existing docker-compose version if it's different.
  file:
    path: "{{ docker_compose_path }}"
    state: absent
  when: >
    docker_compose_current_version.stdout is defined
    and docker_compose_version not in docker_compose_current_version.stdout

- name: Install Docker Compose (if configured).
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    dest: "{{ docker_compose_path }}"
    mode: 0755

# - name: Get docker bridge gateway
#   shell: |
#     docker network inspect bridge | grep Gateway | awk -F\" '{print $4}'
#   register: bridge

# - name: Set docker gateway
#   set_fact:
#     mysql_root_host: "{{ bridge.stdout }}"